"""initial schema

Revision ID: 2f63606c464d
Revises: 
Create Date: 2026-04-19 17:20:51.562543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f63606c464d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=300), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('os_platform', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('fqdn', sa.String(length=500), nullable=True),
    sa.Column('asset_criticality', sa.Integer(), nullable=True),
    sa.Column('business_unit', sa.String(length=200), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_device_name'), 'assets', ['device_name'], unique=True)
    op.create_table('classification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_field', sa.String(length=100), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_value', sa.String(length=500), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_field', 'match_type', 'match_value', 'team_name', name='uq_classification_rule')
    )
    op.create_table('scan_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('rows_parsed', sa.Integer(), nullable=True),
    sa.Column('rows_after_dedup', sa.Integer(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('unique_cves', sa.Integer(), nullable=True),
    sa.Column('unique_devices', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_upload_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('vulnerability_severity', sa.String(length=20), nullable=True),
    sa.Column('exploitability_level', sa.String(length=50), nullable=True),
    sa.Column('software_vendor', sa.String(length=300), nullable=True),
    sa.Column('software_name', sa.String(length=300), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('device_name', sa.String(length=300), nullable=True),
    sa.Column('os_platform', sa.String(length=100), nullable=True),
    sa.Column('recommended_security_update', sa.String(length=500), nullable=True),
    sa.Column('recommended_security_update_id', sa.String(length=200), nullable=True),
    sa.Column('security_update_available', sa.Boolean(), nullable=True),
    sa.Column('recommendation_reference', sa.String(length=500), nullable=True),
    sa.Column('assigned_team', sa.String(length=200), nullable=True),
    sa.Column('classification_tier', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_rating', sa.String(length=20), nullable=True),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=True),
    sa.Column('cisa_kev', sa.Boolean(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['scan_upload_id'], ['scan_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_assigned_team'), 'findings', ['assigned_team'], unique=False)
    op.create_index('ix_findings_cve_device', 'findings', ['cve_id', 'device_name'], unique=False)
    op.create_index(op.f('ix_findings_cve_id'), 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_device_name'), 'findings', ['device_name'], unique=False)
    op.create_index('ix_findings_risk', 'findings', ['risk_score'], unique=False)
    op.create_index('ix_findings_scan', 'findings', ['scan_upload_id'], unique=False)
    op.create_index('ix_findings_team_severity', 'findings', ['assigned_team', 'vulnerability_severity'], unique=False)
    op.create_table('scan_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_upload_id', sa.UUID(), nullable=True),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('unique_cves', sa.Integer(), nullable=True),
    sa.Column('unique_devices', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('kev_count', sa.Integer(), nullable=True),
    sa.Column('sla_breached_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_count', sa.Integer(), nullable=True),
    sa.Column('avg_risk_score', sa.Float(), nullable=True),
    sa.Column('max_risk_score', sa.Float(), nullable=True),
    sa.Column('team_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_upload_id'], ['scan_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_summaries')
    op.drop_index('ix_findings_team_severity', table_name='findings')
    op.drop_index('ix_findings_scan', table_name='findings')
    op.drop_index('ix_findings_risk', table_name='findings')
    op.drop_index(op.f('ix_findings_device_name'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve_id'), table_name='findings')
    op.drop_index('ix_findings_cve_device', table_name='findings')
    op.drop_index(op.f('ix_findings_assigned_team'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('scan_uploads')
    op.drop_table('classification_rules')
    op.drop_index(op.f('ix_assets_device_name'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
